# Generated by Django 2.2 on 2019-04-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_auto_20190409_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='emial',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='admin123@admin.com', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
